### ISSUE TITLE
Unable to parse <template> tag in the body

### ISSUE THREAD

**Issue by jwoertink** [kostya/lexbor#2]
This is almost the same issue as https://github.com/kostya/myhtml/issues/21 but with a small difference

```crystal
input = "<template>Test</template>"
html = Lexbor::Parser.new(input)
html.body!.children.each do |child_tag|
  puts "never gets here"
end

input = "<div><template>Test</template></div>"
html = Lexbor::Parser.new(input)
html.body!.children.each do |child_tag|
  puts "this works"
end
```

If I wrap the `<template>` tag inside of another tag that shows up in the body, then I can access it from `html.body!`. Otherwise I have to use `html.head!` to access it. But the `<template>` tag never goes in the `<head>`, it only goes in the `<body>`.

I looked up the [spec](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element) for this tag which shows it does go in the `<body>`. I also looked up the [lexbor](https://github.com/lexbor/lexbor/blob/c83657de0fdbd3f38827699f81a029c145b35f07/test/files/lexbor/html/html5_test/template.ton) tests that show they are parsing it from within the body. 

I was going to post the issue on their repo, but since I don't know how it works, I wasn't sure how to test it. Do you have any ideas?

**Comment by kostya** [comment]
I added to master method `inner_html=`, try: `node.inner_html = "<template>Test</template>"`, it would parse fragment html.
