### ISSUE TITLE
The doc of 'Node' generated with the 'crystal docs' command is broken.

### ISSUE THREAD

**Issue by yamada-masahiro** [kostya/lexbor#25]
All the other pages have no issues, but only 'node' is unreadable as is seen below.

My compiler version is:
Crystal 1.6.1 (2022-10-21)
LLVM: 14.0.6
Default target: aarch64-apple-darwin21.6.0

<img width="1923" alt="screenshot" src="https://user-images.githubusercontent.com/47566570/198967719-32038553-3023-4cab-a323-4ccdd81eb13a.png">

**Comment by kostya** [comment]
if you know how to fix it, please push pr.

**Comment by yamada-masahiro** [comment]
If I could fix it, I did. Sorry.

When I compared the source of the 'Node' page with the 'parser', I didn't find anything wrong.

**Comment by kostya** [comment]
may be node have multiple files, but parser only 1.

**Comment by nobodywasishere** [comment]
The issue is due to the `</div>` [here](https://github.com/kostya/lexbor/blob/24446a4cfc7aaf1e1f651ec7e8f5e92e3ff16bf7/src/lexbor/node/serialization.cr#L162C35-L162C35). Replacing with a `\</div>` fixes the issue, though the crystal doc generator should really be escaping HTML in doc comments.
