### ISSUE TITLE
Can't install when CMAKE_GENERATOR is set

### ISSUE THREAD

**Issue by iacore** [kostya/lexbor#26]
Environment variable `CMAKE_GENERATOR` sets the default build generator. I have it set to `Ninja`, so the lexbor can't be installed.

Removing the envvar worked.

**Comment by kostya** [comment]
i not familiar wich cmake or others.
if your know how to fix it, send pr.

you can locally build ext:
```
git clone https://github.com/kostya/lexbor.git
cd lexbor/src/ext
make package
```
