### ISSUE TITLE
How to iterate over only elements that are parsed?

### ISSUE THREAD

**Issue by jwoertink** [kostya/lexbor#3]
Given this code:

```crystal
input = "<meta charset="utf-8">"

html = Lexbor::Parser.new(input)
html.document!.children.each do |child_tag|
  puts child_tag.tag_sym
end
```

What I currently get:

```
html
head
body
```

What I want to get:

```
meta
```

With my use case, I don't know if the input will be an HTML snippet, or an entire document. I want to return the same output I get based on the input instead of the user giving me `<meta>` and me giving back `<head><meta></head><body></body>`. Is there a method or something I can call to just iterate over the content in input? (does that make sense? 😅 )

Adding this image to help make clear what I'm trying to do:

If I use `html.document!` or `html.root!`, then I get this:

<img width="992" alt="Screen Shot 2020-07-09 at 4 12 09 PM" src="https://user-images.githubusercontent.com/2391/87099587-0d2b8a80-c1ff-11ea-9a08-60f9843d4749.png">

but I only want `div "hi"` in the output because that's all that's passed in the input.

**Comment by kostya** [comment]
try fragment parsing by `inner_html=`

**Comment by jwoertink** [comment]
So close!! Thanks for responding 😄  Ok, so my example in the picture above works doing that. And actually, doing that also fixes #2 

The last thing it doesn't fix though is this:
<img width="1250" alt="Screen Shot 2020-07-09 at 4 23 40 PM" src="https://user-images.githubusercontent.com/2391/87100199-9abbaa00-c200-11ea-8908-ade31859cd67.png">


It seems to get rid of my `<head>` and `<body>` tags doing that. But maybe I can play around with this more to see if I can get that to work.

**Comment by jwoertink** [comment]
After messing with this for a while, I don't think it'll be possible to do what it is I'm looking for. Here's the code I'm using:

```crystal
html = Lexbor::Parser.new("")
body = html.body!
body.inner_html = @input
body.children.each do |child_tag|
    convert_tag(child_tag)
end
output.to_s
```

My guess is even if you do `Lexbor::Parser.new("")`, the parser will still generate an entire HTML document. So when you do `inner_html` on the `<body>`, and pass in your document, then you'll get:

```html
<html>
<head>
</head>
<body>
  <html>
    <head>
      <title>theme</title>
    </head>
    <body>
     <h1>hi</h1>
    </body>
  </html>
</body>
</html>
```

Then I assume the parser sees invalid markup, and strips it out leaving just the `<title>` and `<h1>`. I guess we can just close out this issue, unless you know of a way that I may be missing?

**Comment by kostya** [comment]
yes parser behaves like browser, it fix html, by moving deleting auto-replacing tags.

**Comment by jwoertink** [comment]
Ah ok. Thanks for your help with this!

**Comment by kostya** [comment]
i think this task can be done with sax parsing, it returns tokens, in order, without modifiyng html. But if html broken (not closed tags, wrong nesting) it would not be fixed.
