### ISSUE TITLE
Moving from myHTML a few questions

### ISSUE THREAD

**Issue by bararchy** [kostya/lexbor#34]
Hi @kostya thanks for the great work on this AND myHTML! 

I have a few questions while we do the migration. does Lexbor has options like: 

```
tree_options: Myhtml::Lib::MyhtmlTreeParseFlags::MyHTML_TREE_PARSE_FLAGS_SKIP_WHITESPACE_TOKEN
```
?

**Comment by kostya** [comment]
In parser no such option. You should do it manually. Only tokenizer https://github.com/kostya/lexbor/blob/master/src/lexbor/tokenizer.cr#L90 have similar option.
