### ISSUE TITLE
Can I get inner_html?

### ISSUE THREAD

**Issue by Dan-Do** [kostya/lexbor#4]
Right now it has setter inner_html=
I want to get inner_html, ex:
```html
<template id="tpl-header"><ul>foo</ul><div>bar</div></template>
```
inner_html should be `<ul>foo</ul><div>bar</div>`
I am using a work around
```crystal
node.to_html.sub(node.to_html(false), "").sub("</"+node.tag_name+">", "")
```
though having a getter should be better.

**Comment by kostya** [comment]
did you try this? https://github.com/kostya/myhtml/issues/19#issuecomment-605740479, just replace myhtml to lexbor

**Comment by Dan-Do** [comment]
It works. Thank you.

**Comment by kostya** [comment]
i added 2 methods, `node#inner_html`  and `#node#inner_pretty_html`, btw: this example with template not work like in myhtml, i not know is it lexbor bug, or my wrapper.
